- _posts/2015-01-09-deis-1-2-happy-new-year.md
- deis-cli/install.sh
- deisctl/install.sh
WIP--please add your comments.
Needs at least:
- ~~better title~~
- more text for the intro paragraph, explain the security fixes specifically, maybe a community thanks?
- ~~more links in "New Features" text (see [last release notes](https://github.com/deis/deis/releases/tag/v1.1.0) for examples)~~
- ~~more bulet points for "New Features" and "Under the Hood" if there are any, see the [CHANGELOG](https://github.com/mboersma/deis/blob/release-1.2.0/CHANGELOG.md)~~
- ~~updates to "Application SSL Support" section?~~
- ~~different author, who wants their name on this one?~~ Props to our Gingeneer, baby
>  feat(post): deis 1.2.0 release

- _posts/2015-03-03-deis-1-4-now-on-azure.md
- deis-cli/install.sh
- deisctl/install.sh
~~Needs a title and summary, probably rewriting of some "What's Next?" sections, and proofreading.~~
~~Needs better summary, rewriting of the app SSL "What's Next?" section, and proofreading.~~
Needs proofreading & suggestions.
> Release 1.4 post

- _posts/2015-04-07-deis-1-5-application-ssl-support.md
- deis-cli/install.sh
- deisctl/install.sh
> Release 1.5

- _posts/2015-04-07-deis-1-5-application-ssl-support.md
still waiting for RTD to update, but here's the patch
> fix(posts): update app ssl link

- _config.yml
- _posts/2015-05-07-deis-1-6-docker-swarm-tech-preview.md
- deis-cli/install.sh
- deisctl/install.sh
> Deis v1.6 release post

- _posts/2015-06-08-deis-1-7-open-roadmap.md
- deis-cli/install.sh
- deisctl/install.sh
> Deis release 1.7 post

- _posts/2015-07-13-deis-1-8-ceph-optional.md
- deis-cli/install.sh
- deisctl/install.sh
Needs proofreading and any suggestions you have to jazz it up a bit. :saxophone:
> Release 1.8

- _posts/2015-08-21-thanks-keerthan-mala.md
Feedback requested, also spicier foods please.
> feat(blog): thanks Keerthan Mala!

- _config.yml
- _posts/2015-08-26-improve-deis-provisioning.md
and a call for community discussion
> feat(post): improving Deis provisioning through rigger

- _posts/2015-09-04-deis-1-10-faster-builder-and-client.md
- deis-cli/install.sh
- deisctl/install.sh
> Release 1.10

- _posts/2015-10-06-deis-1-11-new-logger.md
- deis-cli/install.sh
- deisctl/install.sh
> Release 1.11

- _posts/2015-11-04-deis-1-12-docker-future-proofing.md
- deis-cli/install.sh
- deisctl/install.sh
Feedback welcome! Note that this finally moves artifacts out of the "opdemand" bucket, in conjunction with deis/deis@0bb7b6ea37e3b41b8ce6fdc93d31a8d308ea49fe
TODO:
> Release v1.12.0

- deis-cli/install.sh
- deisctl/install.sh
(To be merged after testing is complete.)
> chore(install.sh): update version to v1.12.2

- deis-cli/install-v2-alpha.sh
instructions incoming at deis/workflow
> feat(deis-cli): introduce install script for v2

- deis-cli/install-v2-alpha.sh
Once https://github.com/deis/workflow/pull/366 gets merged.
> fix(deis-cli): deis-cli filename contains a version now

- deis-cli/install-v2-alpha.sh
> Revert "fix(deis-cli): deis-cli filename contains a version now"

- deis-cli/install.sh
- deisctl/install.sh
> chore(install.sh): update version to v1.13.0

- deis-cli/install.sh
- deisctl/install.sh
See https://github.com/deis/deis/releases/tag/v1.13.3
> chore(install.sh): update version to v1.13.3

- Makefile
Refs https://github.com/deis/deis.com/issues/285
> chore(test): add test target

- s3_website.yml
Closes https://github.com/deis/deis.com/issues/288
Closes https://github.com/deis/deis.com/issues/287
> chore(migration): redirects for community and project urls

- deis-cli/install-v2.sh
This aligns the shell command with what is presented in https://github.com/deis/workflow/blob/master/src/quickstart/install-cli-tools.md
> chore(deis-cli/install-v2.sh): update comment

- deis-cli/install-v2.sh
Reverts deis/deis.io#196 because it caused #197.
> Revert "fix(deis-cli): use POSIX compatible sh"

- deis-cli/install-v2.sh
- fixes #195.
Attempt number 2. Critical changes (vs. #196) @ line 19 + 40
> fix(deis-cli): use POSIX compatible sh

- README.md
> docs(README.md): update for end of maintenance
